version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/sodev-project-front
    overwrite: yes
permissions:
  - object: /home/ubuntu/sodev-project-front
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
